[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program="1.9.5"
borsh="0.9.3"
borsh-derive="0.9.3"

[features]
no-entrypoint=[]

[dev-dependencies]
solana-program-test="1.9.5"
solana-sdk="1.9.5"

[lib]
crate-type=["cdylib", "lib"]
